version: "3.8"

services:
  db:
    image: mysql:8
    container_name: course-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: course_mgmt
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    # healthcheck:
    #   test:
    #     ["CMD-SHELL", "mysql -u root -proot -e 'USE course_mgmt;' || exit 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 10
    #   start_period: 30s

  backend:
    build: ./backend
    container_name: course-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/course_mgmt
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db
      # db:
      #   condition: service_healthy
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: course-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
